<?php

namespace Tests;

use App\Classes\Abstracts\Medabot;
use PHPUnit\Framework\TestCase;

class MedabotDouble extends Medabot
{

}

class MedabotTest extends TestCase
{
    protected $sut;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->sut = new MedabotDouble();
    }

    public function testInstanceOf () : void
    {
        $this->assertInstanceOf(Medabot::class, $this->sut);
    }

    public function testGetColour () : void
    {
        // Test if the method works.
        $this->sut->setColour('red');
        $this->assertEquals('red', $this->sut->getColour());

        // Test if it's dynamic.
        $this->sut->setColour('blue');
        $this->assertEquals('blue', $this->sut->getColour());
    }
}
